agents/urls.py
from django.urls import path

from .views import AgentListView, AgentCreateView, AgentDetailView, AgentUpdateView, AgentDeleteView

app_name = 'agents'

urlpatterns = [
    path('', AgentListView.as_view(), name="agent-list"),
    path('create/', AgentCreateView.as_view(), name="agent-create"),
    path('<int:pk>/', AgentDetailView.as_view(), name="agent-detail"),
    path('<int:pk>/update', AgentUpdateView.as_view(), name='agent-update'),
    path('<int:pk>/delete', AgentDeleteView.as_view(), name='agent-delete'),
]

crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

from leads.views import LandingView
from leads.views import SignUpView, ContactView

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', landing, name='landing'),
    path('', LandingView.as_view(), name='landing'),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('about/', ContactView.as_view(), name='about')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

agents/models.py
from django.db import models

# Create your models here.

agents/views.py
from django.core.mail import send_mail
from django.shortcuts import reverse
from django.views import generic

from leads.forms import AgentCreateForm
from leads.models import Agent
from .mixins import OrganizerAndLoginRequiredMixin


class AgentListView(OrganizerAndLoginRequiredMixin, generic.ListView):
    template_name = 'agents/agent_list.html'
    context_object_name = 'agents'

    def get_queryset(self):
        request_user_profile = self.request.user.userprofile
        return Agent.objects.filter(organisation=request_user_profile)


class AgentCreateView(OrganizerAndLoginRequiredMixin, generic.CreateView):
    template_name = 'agents/agent_create.html'
    form_class = AgentCreateForm

    def get_success_url(self):
        return reverse('agents:agent-list')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.set_password("Password@123")
        user.is_organizer = False
        user.is_agent = True
        user.save()
        agent = Agent(
            user=user,
            organisation=self.request.user.userprofile
        )
        agent.save()

        send_mail(
            subject="You are added as an agent",
            message="You are added to our Costumer Relationship Management system. Please login to get access to your "
                    "dashboard",
            from_email="test@test.com",
            recipient_list=[user.email]
        )

        return super(AgentCreateView, self).form_valid(form)


class AgentDetailView(OrganizerAndLoginRequiredMixin, generic.DetailView):
    template_name = 'agents/agent_detail.html'

    context_object_name = 'agent'

    def get_queryset(self):
        request_user_profile = self.request.user.userprofile
        return Agent.objects.filter(organisation=request_user_profile)


class AgentUpdateView(OrganizerAndLoginRequiredMixin, generic.UpdateView):
    template_name = 'agents/agent_update.html'
    form_class = AgentCreateForm

    def get_queryset(self):
        request_user_profile = self.request.user.userprofile
        return Agent.objects.filter(organisation=request_user_profile)

    def get_success_url(self):
        return reverse('agents:agent-detail', args=([self.object.id]))


class AgentDeleteView(OrganizerAndLoginRequiredMixin, generic.DeleteView):
    template_name = 'agents/agent_delete.html'

    def get_queryset(self):
        request_user_profile = self.request.user.userprofile
        return Agent.objects.filter(organisation=request_user_profile)

    def get_success_url(self):
        return reverse('agents:agent-list')

agents/templates/agents/agent_create.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% block content %}
<div class="max-w-lg mx-auto">
    <a class="hover:text-blue-500" href="{% url 'agents:agent-list' %}">Go back to Agents</a>
    <hr/>

    <h1 class="mt-7 text-4xl text-gray-800">
        Create new Agent
    </h1>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
            Submit
        </button>
    </form>
    <p>Password for your agents will be Password@123</p>
</div>

{% endblock content %}

agents/templates/agents/agent_delete.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
<div class="max-w-lg mx-auto">
    <div class="py-5 border-b border-gray-200">
        <a class="hover:text-blue-500" href="{% url 'agents:agent-list' %}">Go back to Agents</a>
    </div>
    <hr/>
    <h1 class="text-3xl text-gray-800">
        Are you sure you want to delete this Agent ?
    </h1>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit
        </button>
    </form>
</div>

{% endblock content %}

agents/templates/agents/agent_detail.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">Agent</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ agent.user.first_name }} {{ agent.user.last_name }}</h1>
                <div class="flex mb-4">
                    <a href="#" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                        Overview
                    </a>
<!--                    <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">-->
<!--                        Reviews-->
<!--                    </a>-->
                    <a href="{% url 'agents:agent-update' agent.id %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                        Update Details
                    </a>
                </div>
                <p class="leading-relaxed mb-4"></p>
                <div class="flex py-2">
                    <span class="text-gray-500">Last Login</span>
                    <span class="ml-auto text-gray-900">{{ agent.user.last_login }}</span>
                </div>
                <div class="flex border-t border-gray-300 py-2">
                    <span class="text-gray-500">Email</span>
                    <span class="ml-auto text-gray-900">{{agent.user.email}}</span>
                </div>
                <div class="flex border-t border-gray-300 py-2">
                    <span class="text-gray-500">Organiser</span>
                    <span class="ml-auto text-gray-900">{{agent.organisation}}</span>
                </div>
                <div class="flex border-t border-b mb-6 border-gray-300 py-2">
                    <span class="text-gray-500">Date Joined</span>
                    <span class="ml-auto text-gray-900">{{agent.user.date_joined.date}}</span>
                </div>
                <div class="flex">
                    <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                        <a href="{% url 'agents:agent-list' %}">Go Back</a></button>
                    <!--                <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">-->
                    <!--                <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">-->
                    <!--                    <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>-->
                    <!--                </svg>-->
                    <!--                </button>-->
                </div>
            </div>
<!--            <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded"-->
<!--                 src="https://dummyimage.com/400x400">-->
        </div>
    </div>
</section>
{% endblock content %}

agents/templates/agents/agent_list.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-700 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
            <div>
                <h1 class="text-4xl text-gray-800">Agents</h1>
            </div>
            <div>

                <button class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg">
                    <a class="text-gray-500 hover:text-blue-500" href="{% url 'agents:agent-create' %}">Create a new
                        Agent</a>
                </button>
            </div>
        </div>
        <div class="flex flex-wrap -m-4">
            {% for agent in agents %}
            <div class="p-4 lg:w-1/2 md:w-full">
                <div class="flex border-2 rounded-lg border-gray-200 p-8 sm:flex-row flex-col">
                    <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                             stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                            <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                        </svg>
                    </div>
                    <div class="flex-grow">
                        <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
                            {{ agent.user.first_name }} {{ agent.user.last_name }}
                        </h2>
                        <p class="leading-relaxed text-base">
                            Last Login: {{agent.user.last_login}}
                        </p>
                        <a href="{% url 'agents:agent-detail' agent.id %}"
                           class="mt-3 text-indigo-500 inline-flex items-center">
                            View Agent Details
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                 stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                <path d="M5 12h14M12 5l7 7-7 7"></path>
                            </svg>
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock content %}

agents/templates/agents/agent_update.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">Agent</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ agent.user.first_name }} {{ agent.user.last_name }}</h1>
            <div class="flex mb-4">
                <a href="{% url 'agents:agent-detail' agent.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Overview
                </a>
<!--                <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">-->
<!--                    Reviews-->
<!--                </a>-->
                <a href="{% url 'agents:agent-update' agent.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Update Details
                </a>
            </div>
           <form form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
            </form>
            <a href="{% url 'agents:agent-delete' agent.id %}" class="w-1/2 mt-3 flex ml-auto text-white bg-blue-500 border-0 py-2 px-6 focus:outline-none hover:bg-blue-600 rounded">
                Delete
            </a>
        </div>
<!--        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">-->
      </div>
    </div>
  </section>
{% endblock content %}