agents/urls.py
from django.urls import path

from .views import AgentListView, AgentCreateView, AgentDetailView, AgentUpdateView, AgentDeleteView

app_name = 'agents'

urlpatterns = [
    path('', AgentListView.as_view(), name="agent-list"),
    path('create/', AgentCreateView.as_view(), name="agent-create"),
    path('<int:pk>/', AgentDetailView.as_view(), name="agent-detail"),
    path('<int:pk>/update', AgentUpdateView.as_view(), name='agent-update'),
    path('<int:pk>/delete', AgentDeleteView.as_view(), name='agent-delete'),
]

crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

from leads.views import LandingView
from leads.views import SignUpView, ContactView

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', landing, name='landing'),
    path('', LandingView.as_view(), name='landing'),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('about/', ContactView.as_view(), name='about')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from .views import (
    LeadListView,
    LeadDetailView,
    LeadCreateView,
    LeadUpdateView,
    LeadDeleteView,
    AssignLeadView,
    CategoryListView,
    CategoryDetailView,
    LeadCategoryUpdateView
)

app_name = 'leads'

urlpatterns = [
    # path('', lead_list, name='lead-list'),
    path('', LeadListView.as_view(), name='lead-list'),
    path('<int:pk>/', LeadDetailView.as_view(), name='lead-detail'),
    path('create/', LeadCreateView.as_view(), name='lead-create'),
    path('<int:pk>/update', LeadUpdateView.as_view(), name='lead-update'),
    path('<int:pk>/delete', LeadDeleteView.as_view(), name='lead-delete'),
    path('<int:pk>/assign', AssignLeadView.as_view(), name='lead-assign'),
    path('categories/', CategoryListView.as_view(), name="category-list"),
    path('<int:pk>/category', CategoryDetailView.as_view(), name='category-detail'),
    path('<int:pk>/category-update', LeadCategoryUpdateView.as_view(), name='category-update'),
]

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Costumer Relationship manager</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
<div class="max-w-7xl mx-auto">
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock content %}
</div>

</body>
</html>

templates/contact.html
{%extends 'base.html'%}


{% block content %}

<section class="text-gray-600 body-font">
    <div class="container flex flex-wrap px-5 py-24 mx-auto items-center">
        <div class="md:w-1/2 md:pr-12 md:py-8 md:border-r md:border-b-0 mb-10 md:mb-0 pb-10 border-b border-gray-200">
            <h1 class="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900">Harsh Gupta</h1>
            <p class="leading-relaxed text-base">I am currently pursuing my under graduation in Information Technology
                Engineering from Maharaja Agrasen Institute of Technology in New Delhi. I mostly engage in Backend
                Development with satisfactory knowledge of frontend frameworks. I am a keen learner ready to learn new
                and exciting technologies. </p>
            <a href="https://github.com/harshhx/Django-CRM" class="text-indigo-500 inline-flex items-center mt-4">Github repo
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                     class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                    <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
            </a>
          <p class="leading-relaxed text-base">Mail me new opportunities or queries at hg070401@gmail.com</p>
        </div>
        <div class="flex flex-col md:w-1/2 md:pl-12">
            <h2 class="title-font font-semibold text-gray-800 tracking-wider text-sm mb-3">CATEGORIES</h2>
            <nav class="flex flex-wrap list-none -mb-1">
                <li class="lg:w-1/3 mb-1 w-1/2">
                    <a href="https://www.harshgupta.live/" class="text-gray-600 hover:text-blue-800">More about me</a>
                </li>
                <li class="lg:w-1/3 mb-1 w-1/2">
                    <a href="https://www.linkedin.com/in/harshhx/" class="text-gray-600 hover:text-blue-800">Linkedin</a>
                </li>
                <li class="lg:w-1/3 mb-1 w-1/2">
                    <a href="https://www.instagram.com/harshhx/" class="text-gray-600 hover:text-blue-800">Instagram</a>
                </li>
<!--                <li class="lg:w-1/3 mb-1 w-1/2">-->
<!--                    <a class="text-gray-600 hover:text-gray-800">Fourth Link</a>-->
<!--                </li>-->
<!--                <li class="lg:w-1/3 mb-1 w-1/2">-->
<!--                    <a class="text-gray-600 hover:text-gray-800">Fifth Link</a>-->
<!--                </li>-->
<!--                <li class="lg:w-1/3 mb-1 w-1/2">-->
<!--                    <a class="text-gray-600 hover:text-gray-800">Sixth Link</a>-->
<!--                </li>-->
<!--                <li class="lg:w-1/3 mb-1 w-1/2">-->
<!--                    <a class="text-gray-600 hover:text-gray-800">Seventh Link</a>-->
<!--                </li>-->
<!--                <li class="lg:w-1/3 mb-1 w-1/2">-->
<!--                    <a class="text-gray-600 hover:text-gray-800">Eighth Link</a>-->
<!--                </li>-->
            </nav>
        </div>
    </div>
</section>

{% endblock content %}

templates/landing.html
{%extends 'base.html'%}


{% block content %}

<section class="text-gray-600 body-font">
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
        <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero"
             src="https://cdn.dribbble.com/users/988852/screenshots/4371058/sales-team2.png">
        <div class="text-center lg:w-2/3 w-full">
            <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">Costumer Relationship
                Manager</h1>
            <p class="mb-8 leading-relaxed">This is a django project that helps an organisation to manage all its leads
                and assign them to an agent. This interactive dashboard will make your work a lot easier.</p>
            <div class="flex justify-center">
                <button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">
                    <a href="{% url 'login' %}">
                        Log In
                    </a>
                </button>
                <button class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg">
                    <a href="{% url 'signup' %}">Sign Up</a>
                </button>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

templates/navbar.html
<header class="text-gray-600 body-font">
    <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
        <a href="{% url 'landing' %}" class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round"
                 stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full"
                 viewBox="0 0 24 24">
                <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
            </svg>
            <span class="ml-3 text-xl">Costumer Relationship Manager</span>
        </a>
        <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
            <a href="{% url 'about' %}" class="mr-5 hover:text-gray-900">About Us</a>
            {% if not request.user.is_authenticated %}
            <a href="{% url 'signup' %}" class="mr-5 hover:text-gray-900">Sign Up</a>
            {% else %}
            <a href="{% url 'leads:lead-list' %}" class="mr-5 hover:text-gray-900">Leads</a>
            {% if request.user.is_organizer %}
            <a href="{% url 'agents:agent-list' %}" class="mr-5 hover:text-gray-900">Agents</a>
            {% endif %}
            {% endif %}
        </nav>
        {% if request.user.is_authenticated %}
        Logged in as: {{request.user.username}}
        <button class="ml-3 inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
            <a href="{% url 'logout' %}">Log Out</a>
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                 class="w-4 h-4 ml-1" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
        </button>
        {% else %}
        <button class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
            <a href="{% url 'login' %}">Login</a>
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                 class="w-4 h-4 ml-1" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
        </button>
        {% endif %}
    </div>
</header>